version: '3'

services:
  mysql:
    image: sempron123/cloth-webshop:mysqlserver
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test

  rabbit_queue:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"